# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtWidgets, QtGui

class UI_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 690)

        """  
        MODEL START TIME AND DURATION FRAME
        """
        self.start_frame = QtWidgets.QFrame(MainWindow)
        self.start_frame.setGeometry(QtCore.QRect(10, 40, 740, 60))
        self.start_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.start_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.start_frame.setObjectName("start_frame")

        self.startFrame_label = QtWidgets.QLabel(MainWindow)
        self.startFrame_label.raise_()
        self.startFrame_label.setGeometry(QtCore.QRect(20, 30, 195, 20))
        self.startFrame_label.setMinimumSize(QtCore.QSize(0, 0))
        self.startFrame_label.setAutoFillBackground(True)
        self.startFrame_label.setScaledContents(False)
        self.startFrame_label.setAlignment(QtCore.Qt.AlignCenter)
        self.startFrame_label.setWordWrap(False)
        self.startFrame_label.setObjectName("startFrame_label")
        # font = QtGui.QFont()
        # font.setBold(True)
        # self.startFrame_label.setFont(font)

        self.start_horLay = QtWidgets.QHBoxLayout(self.start_frame)
        self.start_horLay.setContentsMargins(5, 0, 5, 0)
        self.start_horLay.setObjectName("start_horLay")

        self.start_strtDate_label = QtWidgets.QLabel(self.start_frame)
        self.start_strtDate_label.setMaximumSize(QtCore.QSize(120, 16777215))        
        self.start_strtDate_label.setObjectName("start_strtDate_label")
        self.start_horLay.addWidget(self.start_strtDate_label)

        self.start_strtDateTime = QtWidgets.QDateTimeEdit(self.start_frame, calendarPopup=True)
        self.start_strtDateTime.setDateTime(QtCore.QDateTime.currentDateTime().addDays(-4))
        self.start_strtDateTime.setMaximumSize(QtCore.QSize(150, 16777215))
        self.start_strtDateTime.setObjectName("start_strtDateTime")
        self.start_horLay.addWidget(self.start_strtDateTime)

        start_spacerItem_1 = QtWidgets.QSpacerItem(170, 16777215, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        start_spacerItem_1.setAlignment(QtCore.Qt.AlignLeft)
        self.start_horLay.addItem(start_spacerItem_1)

        self.start_endDate_label = QtWidgets.QLabel(self.start_frame)
        # self.start_endDate_label.setAutoFillBackground(True)
        # self.start_endDate_label.setScaledContents(False)
        # self.start_endDate_label.setWordWrap(False)
        self.start_endDate_label.setMaximumSize(QtCore.QSize(120, 16777215))
        self.start_endDate_label.setObjectName("start_endDate_label")
        self.start_horLay.addWidget(self.start_endDate_label)

        self.start_endDateTime = QtWidgets.QDateTimeEdit(self.start_frame, calendarPopup=True)
        self.start_endDateTime.setDateTime(QtCore.QDateTime.currentDateTime())
        self.start_endDateTime.setMaximumSize(QtCore.QSize(150, 16777215))
        self.start_endDateTime.setObjectName("start_endDateTime")
        self.start_horLay.addWidget(self.start_endDateTime)

        # start_spacerItem_2 = QtWidgets.QSpacerItem(30, 16777215, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        # self.start_horLay.addItem(start_spacerItem_2)        

        """
        WIND FRAME
        """        
        self.wind_frame = QtWidgets.QFrame(MainWindow)
        self.wind_frame.setGeometry(QtCore.QRect(10, 120, 740, 120))
        self.wind_frame.setAutoFillBackground(False)
        self.wind_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.wind_frame.setFrameShadow(QtWidgets.QFrame.Raised)        
        self.wind_frame.setObjectName("wind_frame")

        self.windFrame_label = QtWidgets.QLabel(MainWindow)
        self.windFrame_label.raise_()
        self.windFrame_label.setGeometry(QtCore.QRect(20, 110, 40, 20))
        self.windFrame_label.setMinimumSize(QtCore.QSize(0, 0))
        self.windFrame_label.setAutoFillBackground(True)
        self.windFrame_label.setScaledContents(False)
        self.windFrame_label.setAlignment(QtCore.Qt.AlignCenter)
        self.windFrame_label.setWordWrap(False)
        self.windFrame_label.setObjectName("windFrame_label")

        self.wind_gridLayout = QtWidgets.QGridLayout(self.wind_frame)
        self.wind_gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.wind_gridLayout.setContentsMargins(5, 0, 5, 0)
        self.wind_gridLayout.setVerticalSpacing(6)
        self.wind_gridLayout.setObjectName("wind_gridLayout")

        self.wind_file_radioButton = QtWidgets.QRadioButton(self.wind_frame)
        self.wind_file_radioButton.setChecked(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.wind_file_radioButton.setSizePolicy(sizePolicy)
        self.wind_file_radioButton.setObjectName("wind_file_radioButton")
        self.wind_gridLayout.addWidget(self.wind_file_radioButton, 0, 0, 1, 1)

        self.wind_file_select_lnEd = QtWidgets.QLineEdit(self.wind_frame)
        self.wind_file_select_lnEd.setObjectName("wind_file_select_lnEd")
        self.wind_gridLayout.addWidget(self.wind_file_select_lnEd, 0, 1, 1, 8)

        self.wind_file_select_Btn = QtWidgets.QPushButton(self.wind_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.wind_file_select_Btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.wind_file_select_Btn.setSizePolicy(sizePolicy)
        self.wind_file_select_Btn.setObjectName("wind_file_select_Btn")
        self.wind_gridLayout.addWidget(self.wind_file_select_Btn, 0, 9, 1, 1)        

        self.wind_cnst_radioButton = QtWidgets.QRadioButton(self.wind_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.wind_cnst_radioButton.setSizePolicy(sizePolicy)
        self.wind_cnst_radioButton.setObjectName("wind_cnst_radioButton")
        self.wind_gridLayout.addWidget(self.wind_cnst_radioButton, 1, 0, 1, 1)

        self.wind_mag_label = QtWidgets.QLabel(self.wind_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.wind_mag_label.setSizePolicy(sizePolicy)
        self.wind_mag_label.setObjectName("wind_mag_label")
        self.wind_gridLayout.addWidget(self.wind_mag_label, 1, 1, 1, 1)
        
        self.wind_mag_lnEdt = QtWidgets.QLineEdit(self.wind_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.wind_mag_lnEdt.setSizePolicy(sizePolicy)
        self.wind_mag_lnEdt.setMaximumSize(QtCore.QSize(75, 16777215))
        self.wind_mag_lnEdt.setObjectName("wind_mag_lnEdt")
        self.wind_gridLayout.addWidget(self.wind_mag_lnEdt, 1, 2, 1, 1)

        self.wind_magUnit_label = QtWidgets.QLabel(self.wind_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.wind_magUnit_label.setSizePolicy(sizePolicy)
        self.wind_magUnit_label.setObjectName("wind_magUnit_label")
        self.wind_gridLayout.addWidget(self.wind_magUnit_label, 1, 3, 1, 1)

        wind_spacerItem_14 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.wind_gridLayout.addItem(wind_spacerItem_14, 1, 4, 1, 1)

        self.wind_dir_label = QtWidgets.QLabel(self.wind_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.wind_dir_label.setSizePolicy(sizePolicy)
        self.wind_dir_label.setObjectName("wind_dir_label")
        self.wind_gridLayout.addWidget(self.wind_dir_label, 1, 5, 1, 1)

        self.wind_dir_lnEdt = QtWidgets.QLineEdit(self.wind_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.wind_dir_lnEdt.setSizePolicy(sizePolicy)
        self.wind_dir_lnEdt.setMaximumSize(QtCore.QSize(75, 16777215))
        self.wind_dir_lnEdt.setObjectName("wind_dir_lnEdt")
        self.wind_gridLayout.addWidget(self.wind_dir_lnEdt, 1, 6, 1, 1)

        self.wind_dirUnit_label = QtWidgets.QLabel(self.wind_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.wind_dirUnit_label.setSizePolicy(sizePolicy)
        self.wind_dirUnit_label.setObjectName("wind_dirUnit_label")
        self.wind_gridLayout.addWidget(self.wind_dirUnit_label, 1, 7, 1, 1)

        wind_spacerItem_18 = QtWidgets.QSpacerItem(190, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.wind_gridLayout.addItem(wind_spacerItem_18, 1, 8, 1, 1)      
     
        """
        CURRENT FRAME
        """
        self.current_frame = QtWidgets.QFrame(MainWindow)
        self.current_frame.setGeometry(QtCore.QRect(10, 260, 740, 120))
        self.current_frame.setAutoFillBackground(False)
        self.current_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.current_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.current_frame.setObjectName("current_frame")

        self.currentFrame_label = QtWidgets.QLabel(MainWindow)
        self.currentFrame_label.raise_()
        self.currentFrame_label.setGeometry(QtCore.QRect(20, 250, 60, 20))
        self.currentFrame_label.setMinimumSize(QtCore.QSize(0, 0))
        self.currentFrame_label.setAutoFillBackground(True)
        self.currentFrame_label.setScaledContents(False)
        self.currentFrame_label.setAlignment(QtCore.Qt.AlignCenter)
        self.currentFrame_label.setWordWrap(False)
        self.currentFrame_label.setObjectName("currentFrame_label")

        self.current_gridLayout = QtWidgets.QGridLayout(self.current_frame)
        self.current_gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.current_gridLayout.setContentsMargins(5, 0, 5, 0)
        self.current_gridLayout.setVerticalSpacing(6)
        self.current_gridLayout.setObjectName("current_gridLayout")

        self.current_file_radioButton = QtWidgets.QRadioButton(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.current_file_radioButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.current_file_radioButton.setSizePolicy(sizePolicy)
        self.current_file_radioButton.setChecked(True)
        self.current_file_radioButton.setObjectName("current_file_radioButton")
        self.current_gridLayout.addWidget(self.current_file_radioButton, 0, 0, 1, 1)

        self.current_file_select_lnEd = QtWidgets.QLineEdit(self.current_frame)
        self.current_file_select_lnEd.setObjectName("current_file_select_lnEd")
        self.current_gridLayout.addWidget(self.current_file_select_lnEd, 0, 1, 1, 15)

        self.current_file_select_Btn = QtWidgets.QPushButton(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.current_file_select_Btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.current_file_select_Btn.setSizePolicy(sizePolicy)
        self.current_file_select_Btn.setObjectName("current_file_select_Btn")
        self.current_gridLayout.addWidget(self.current_file_select_Btn, 0, 16, 1, 1)

        self.current_cnst_radioButton = QtWidgets.QRadioButton(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.current_cnst_radioButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.current_cnst_radioButton.setSizePolicy(sizePolicy)
        self.current_cnst_radioButton.setObjectName("current_cnst_radioButton")
        self.current_gridLayout.addWidget(self.current_cnst_radioButton, 1, 0, 1, 1)

        self.current_mag_label = QtWidgets.QLabel(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.current_mag_label.setSizePolicy(sizePolicy)
        self.current_mag_label.setObjectName("current_mag_label")
        self.current_gridLayout.addWidget(self.current_mag_label, 1, 1, 1, 1)

        self.current_mag_lnEdt = QtWidgets.QLineEdit(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.current_mag_lnEdt.setSizePolicy(sizePolicy)
        self.current_mag_lnEdt.setMaximumSize(QtCore.QSize(50, 16777215))        
        self.current_mag_lnEdt.setObjectName("current_mag_lnEdt")
        self.current_gridLayout.addWidget(self.current_mag_lnEdt, 1, 2, 1, 1)

        self.current_magUnit_label = QtWidgets.QLabel(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.current_magUnit_label.setSizePolicy(sizePolicy)
        self.current_magUnit_label.setObjectName("current_magUnit_label")
        self.current_gridLayout.addWidget(self.current_magUnit_label, 1, 3, 1, 1)        

        current_spacerItem_14 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.current_gridLayout.addItem(current_spacerItem_14, 1, 4, 1, 1)

        self.current_dir_label = QtWidgets.QLabel(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.current_dir_label.setSizePolicy(sizePolicy)
        self.current_dir_label.setObjectName("current_dir_label")
        self.current_gridLayout.addWidget(self.current_dir_label, 1, 5, 1, 1)

        self.current_dir_lnEdt = QtWidgets.QLineEdit(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.current_dir_lnEdt.setSizePolicy(sizePolicy)
        self.current_dir_lnEdt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.current_dir_lnEdt.setObjectName("current_dir_lnEdt")
        self.current_gridLayout.addWidget(self.current_dir_lnEdt, 1, 6, 1, 1)

        self.current_dirUnit_label = QtWidgets.QLabel(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.current_dirUnit_label.setSizePolicy(sizePolicy)
        self.current_dirUnit_label.setObjectName("current_dirUnit_label")
        self.current_gridLayout.addWidget(self.current_dirUnit_label, 1, 7, 1, 1)

        current_spacerItem_14 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.current_gridLayout.addItem(current_spacerItem_14, 1, 8, 1, 1)        

        self.current_sal_label = QtWidgets.QLabel(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.current_sal_label.setSizePolicy(sizePolicy)
        self.current_sal_label.setObjectName("current_sal_label")
        self.current_gridLayout.addWidget(self.current_sal_label, 1, 9, 1, 1)        

        self.current_sal_lnEdt = QtWidgets.QLineEdit(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.current_sal_lnEdt.setSizePolicy(sizePolicy)
        self.current_sal_lnEdt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.current_sal_lnEdt.setObjectName("current_sal_lnEdt")
        self.current_gridLayout.addWidget(self.current_sal_lnEdt, 1, 10, 1, 1)

        self.current_salUnit_label = QtWidgets.QLabel(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.current_salUnit_label.setSizePolicy(sizePolicy)
        self.current_salUnit_label.setObjectName("current_salUnit_label")
        self.current_gridLayout.addWidget(self.current_salUnit_label, 1, 11, 1, 1)

        current_spacerItem_1_12 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.current_gridLayout.addItem(current_spacerItem_1_12, 1, 12, 1, 1)        

        self.current_temp_label = QtWidgets.QLabel(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.current_temp_label.setSizePolicy(sizePolicy)
        self.current_temp_label.setObjectName("current_temp_label")
        self.current_gridLayout.addWidget(self.current_temp_label, 1, 13, 1, 1)            

        self.current_temp_lnEdt = QtWidgets.QLineEdit(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.current_temp_lnEdt.setSizePolicy(sizePolicy)
        self.current_temp_lnEdt.setMaximumSize(QtCore.QSize(50, 16777215))
        self.current_temp_lnEdt.setObjectName("current_temp_lnEdt")
        self.current_gridLayout.addWidget(self.current_temp_lnEdt, 1, 14, 1, 1)

        self.current_tempUnit_label = QtWidgets.QLabel(self.current_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.current_tempUnit_label.setSizePolicy(sizePolicy)
        self.current_tempUnit_label.setObjectName("current_tempUnit_label")
        self.current_gridLayout.addWidget(self.current_tempUnit_label, 1, 15, 1, 1)        

        current_spacerItem_18 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.current_gridLayout.addItem(current_spacerItem_18, 1, 16, 1, 1)  

        """
        RELEASE FRAME
        """
        self.release_frame = QtWidgets.QFrame(MainWindow)
        self.release_frame.setGeometry(QtCore.QRect(10, 400, 740, 240))
        self.release_frame.setAutoFillBackground(False)
        self.release_frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.release_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.release_frame.setObjectName("release_frame")

        self.releaseFrame_label = QtWidgets.QLabel(MainWindow)
        self.releaseFrame_label.raise_()
        self.releaseFrame_label.setGeometry(QtCore.QRect(20, 390, 60, 20))
        self.releaseFrame_label.setMinimumSize(QtCore.QSize(0, 0))
        self.releaseFrame_label.setAutoFillBackground(True)
        self.releaseFrame_label.setScaledContents(False)
        self.releaseFrame_label.setAlignment(QtCore.Qt.AlignCenter)
        self.releaseFrame_label.setWordWrap(False)
        self.releaseFrame_label.setObjectName("releaseFrame_label")

        self.release_gridLayout = QtWidgets.QGridLayout(self.release_frame)
        self.release_gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.release_gridLayout.setContentsMargins(5, 0, 5, 0)
        self.release_gridLayout.setVerticalSpacing(6)
        self.release_gridLayout.setObjectName("release_gridLayout")

        self.releaseOutput_label = QtWidgets.QLabel(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.releaseOutput_label.setSizePolicy(sizePolicy)
        self.releaseOutput_label.setObjectName("releaseOutput_label")
        self.release_gridLayout.addWidget(self.releaseOutput_label, 0, 0, 1, 1)

        self.release_output_lnEdt = QtWidgets.QLineEdit(self.release_frame)
        self.release_output_lnEdt.setFixedSize(QtCore.QSize(567, 16777215))
        self.release_output_lnEdt.setObjectName("release_output_lnEd")
        self.release_gridLayout.addWidget(self.release_output_lnEdt, 0, 1, 1, 4)

        self.release_output_Btn = QtWidgets.QPushButton(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.release_output_Btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.release_output_Btn.setSizePolicy(sizePolicy)
        self.release_output_Btn.setObjectName("release_output_Btn")
        self.release_gridLayout.addWidget(self.release_output_Btn, 0, 5, 1, 1, alignment=QtCore.Qt.AlignRight)

        self.release_pollutant_label = QtWidgets.QLabel(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.release_pollutant_label.setSizePolicy(sizePolicy)
        self.release_pollutant_label.setObjectName("release_pollutant_label")
        self.release_gridLayout.addWidget(self.release_pollutant_label, 1, 0, 1, 1)

        self.release_pollutant_comboBox = QtWidgets.QComboBox(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.release_pollutant_comboBox.setSizePolicy(sizePolicy)
        self.release_pollutant_comboBox.setMinimumSize(QtCore.QSize(175, 0))
        self.release_pollutant_comboBox.setObjectName("release_pollutant_comboBox")
        self.release_gridLayout.addWidget(self.release_pollutant_comboBox, 1, 1, 1, 1)

        # release_spacerItem_12 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        # self.release_gridLayout.addItem(release_spacerItem_12, 1, 2, 1, 1)        

        self.release_pollutant_file_label = QtWidgets.QLabel(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.release_pollutant_file_label.setSizePolicy(sizePolicy)
        self.release_pollutant_file_label.setObjectName("release_pollutant_file_label")
        self.release_gridLayout.addWidget(self.release_pollutant_file_label, 1, 2, 1, 1)

        self.release_pollutant_lnEdt = QtWidgets.QLineEdit(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        self.release_pollutant_lnEdt.setSizePolicy(sizePolicy)
        self.release_pollutant_lnEdt.setMinimumSize(QtCore.QSize(320, 0))
        self.release_pollutant_lnEdt.setObjectName("release_pollutant_lnEdt")
        self.release_gridLayout.addWidget(self.release_pollutant_lnEdt, 1, 3, 1, 1)     

        self.release_pollutant_file_Btn = QtWidgets.QPushButton(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.release_pollutant_file_Btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.release_pollutant_file_Btn.setSizePolicy(sizePolicy)
        self.release_pollutant_file_Btn.setObjectName("release_pollutant_file_Btn")
        self.release_gridLayout.addWidget(self.release_pollutant_file_Btn, 1, 5, 1, 1, alignment=QtCore.Qt.AlignRight)




        self.release_amount_label = QtWidgets.QLabel(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.release_amount_label.setSizePolicy(sizePolicy)
        self.release_amount_label.setObjectName("release_amount_label")
        self.release_gridLayout.addWidget(self.release_amount_label, 2, 0, 1, 1)

        self.release_amount_lnEdt = QtWidgets.QLineEdit(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        self.release_amount_lnEdt.setSizePolicy(sizePolicy)
        self.release_amount_lnEdt.setMinimumSize(QtCore.QSize(175, 16777215))
        self.release_amount_lnEdt.setObjectName("release_amount_lnEdt")
        self.release_gridLayout.addWidget(self.release_amount_lnEdt, 2, 1, 1, 1) 

        self.release_amount_comboBox = QtWidgets.QComboBox(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.release_amount_comboBox.setSizePolicy(sizePolicy)
        self.release_amount_comboBox.setMaximumSize(QtCore.QSize(180, 16777215))
        self.release_amount_comboBox.setObjectName("release_amount_comboBox")
        self.release_gridLayout.addWidget(self.release_amount_comboBox, 2, 2, 1, 1, alignment=QtCore.Qt.AlignLeft)

        self.release_strtDate_label = QtWidgets.QLabel(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        self.release_strtDate_label.setSizePolicy(sizePolicy)
        self.release_strtDate_label.setObjectName("release_strtDate_label")
        self.release_gridLayout.addWidget(self.release_strtDate_label, 3, 0, 1, 1)

        self.release_start_DateTime = QtWidgets.QDateTimeEdit(self.release_frame, calendarPopup=True)
        self.release_start_DateTime.setDateTime(QtCore.QDateTime.currentDateTime().addDays(-3))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.release_start_DateTime.setSizePolicy(sizePolicy)
        self.release_start_DateTime.setMaximumSize(QtCore.QSize(180, 16777215))
        self.release_start_DateTime.setObjectName("release_start_DateTime")
        self.release_gridLayout.addWidget(self.release_start_DateTime, 3, 1, 1, 1)

        release_spacerItem_32 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.release_gridLayout.addItem(release_spacerItem_32, 3, 2, 1, 1)

        self.release_latitude_label = QtWidgets.QLabel(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        self.release_latitude_label.setSizePolicy(sizePolicy)
        self.release_latitude_label.setObjectName("release_latitude_label")
        self.release_gridLayout.addWidget(self.release_latitude_label, 3, 3, 1, 1, alignment=QtCore.Qt.AlignRight)
        
        self.release_latitude_lnEdt = QtWidgets.QLineEdit(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        self.release_latitude_lnEdt.setSizePolicy(sizePolicy)
        self.release_latitude_lnEdt.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.release_latitude_lnEdt.setObjectName("release_latitude_lnEdt")
        self.release_gridLayout.addWidget(self.release_latitude_lnEdt, 3, 4, 1, 1)

        self.release_latDir_label = QtWidgets.QLabel(self.release_frame)
        self.release_latDir_label.setObjectName("release_latDir_label")
        self.release_gridLayout.addWidget(self.release_latDir_label, 3, 5, 1, 1)

        self.release_endDate_label = QtWidgets.QLabel(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        self.release_endDate_label.setSizePolicy(sizePolicy)
        self.release_endDate_label.setObjectName("release_endDate_label")
        self.release_gridLayout.addWidget(self.release_endDate_label, 4, 0, 1, 1)

        self.release_end_DateTime = QtWidgets.QDateTimeEdit(self.release_frame, calendarPopup=True)
        self.release_end_DateTime.setDateTime(QtCore.QDateTime.currentDateTime().addDays(-1))
        self.release_end_DateTime.setMaximumSize(QtCore.QSize(180, 16777215))
        self.release_end_DateTime.setObjectName("release_end_DateTime")
        self.release_gridLayout.addWidget(self.release_end_DateTime, 4, 1, 1, 1)

        self.release_longitude_label = QtWidgets.QLabel(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        self.release_longitude_label.setSizePolicy(sizePolicy)
        self.release_longitude_label.setObjectName("release_longitude_label")
        self.release_gridLayout.addWidget(self.release_longitude_label, 4, 3, 1, 1, alignment=QtCore.Qt.AlignRight)

        self.release_longitude_lnEdt = QtWidgets.QLineEdit(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        self.release_longitude_lnEdt.setSizePolicy(sizePolicy)
        self.release_longitude_lnEdt.setObjectName("release_longitude_lnEdt")
        self.release_gridLayout.addWidget(self.release_longitude_lnEdt, 4, 4, 1, 1)

        self.release_lonDir_label = QtWidgets.QLabel(self.release_frame)
        self.release_lonDir_label.setObjectName("release_lonDir_label")
        self.release_gridLayout.addWidget(self.release_lonDir_label, 4, 5, 1, 1)

        self.release_depth_label = QtWidgets.QLabel(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        self.release_depth_label.setSizePolicy(sizePolicy)
        self.release_depth_label.setObjectName("release_depth_label")
        self.release_gridLayout.addWidget(self.release_depth_label, 5, 3, 1, 1, alignment=QtCore.Qt.AlignRight)

        self.release_depth_lnEdt = QtWidgets.QLineEdit(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.release_depth_lnEdt.sizePolicy().hasHeightForWidth())
        self.release_depth_lnEdt.setSizePolicy(sizePolicy)
        self.release_depth_lnEdt.setObjectName("release_depth_lnEdt")
        self.release_gridLayout.addWidget(self.release_depth_lnEdt, 5, 4, 1, 1)

        self.release_depthUnit_label = QtWidgets.QLabel(self.release_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        self.release_depthUnit_label.setSizePolicy(sizePolicy)
        self.release_depthUnit_label.setObjectName("release_depthUnit_label")
        self.release_gridLayout.addWidget(self.release_depthUnit_label, 5, 5, 1, 1)
 
        self.close_button = QtWidgets.QPushButton(MainWindow)
        self.close_button.setGeometry(QtCore.QRect(545, 650, 100, 25))
        icon = MainWindow.style().standardIcon(getattr(QtWidgets.QStyle, "SP_DialogCloseButton"))
        self.close_button.setObjectName("close_button")
        self.close_button.setIcon(icon)

        self.start_button = QtWidgets.QPushButton(MainWindow)
        self.start_button.setGeometry(QtCore.QRect(650, 650, 100, 25))
        icon = MainWindow.style().standardIcon(getattr(QtWidgets.QStyle, "SP_DialogOkButton"))
        self.start_button.setObjectName("start_button")
        self.start_button.setIcon(icon)

        # self.central_widget = QtWidgets.QWidget(MainWindow)
        # self.central_widget.setObjectName("central_widget")
        # MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 25))
        self.menubar.setObjectName("menubar")
        self.menubar.setAutoFillBackground(True)
        self.menubar.setStyleSheet("""QMenuBar {
            background-color: #f5f5f5;
            }""")
        self.menu_Menu = QtWidgets.QMenu(self.menubar)
        self.menu_Menu.setObjectName("menu_Menu")
        MainWindow.setMenuBar(self.menubar)
        self.action_new = QtWidgets.QAction(MainWindow)
        self.action_new.setObjectName("action_new")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.menu_Menu.addAction(self.action_new)
        self.menu_Menu.addAction(self.action_about)
        self.menubar.addAction(self.menu_Menu.menuAction())

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setGeometry(QtCore.QRect(0, 0, 780, 25))
        MainWindow.setStatusBar(self.statusbar)
        self.statusbar.setObjectName("statusbar")
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setStyleSheet("""QStatusBar {
            background-color: #f5f5f5;
            }""")        

        # # Display MainWindow at the center of the screen
        # self.frame_geometry = MainWindow.frameGeometry()
        # self.center_position = QtWidgets.QDesktopWidget().availableGeometry().center()
        # self.frame_geometry.moveCenter(self.center_position)
        # MainWindow.move(self.frame_geometry.topLeft())        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        """
        Translation function
        """
        _translate = QtCore.QCoreApplication.translate
        self.start_strtDate_label.setText(_translate("MainWindow", "Model Start Date:"))
        self.start_endDate_label.setText(_translate("MainWindow", "Model End Date:"))
        self.startFrame_label.setText(_translate("MainWindow", "Model Start Time and Duration"))
        self.windFrame_label.setText(_translate("MainWindow", "Wind"))
        self.wind_file_radioButton.setText(_translate("MainWindow", "From File:"))
        self.wind_file_select_lnEd.setToolTip(_translate("MainWindow", "Path to the input wind NetCDF file"))
        self.wind_file_select_Btn.setText(_translate("MainWindow", "..."))
        self.wind_mag_label.setText(_translate("MainWindow", "Magnitude:"))
        self.wind_magUnit_label.setText(_translate("MainWindow", "m/s"))
        self.wind_cnst_radioButton.setText(_translate("MainWindow", "Constant:"))
        self.wind_dir_label.setText(_translate("MainWindow", "Direction:"))
        self.wind_dir_lnEdt.setToolTip(_translate("MainWindow", "0 ⩽ d° < 360"))
        self.wind_dirUnit_label.setText(_translate("MainWindow", "North"))
        self.current_file_radioButton.setText(_translate("MainWindow", "From File:"))
        self.current_file_select_lnEd.setToolTip(_translate("MainWindow", "Path to the input current NetCDF file"))
        self.current_file_select_Btn.setText(_translate("MainWindow", "..."))
        self.current_mag_label.setText(_translate("MainWindow", "Mag.:"))
        self.current_magUnit_label.setText(_translate("MainWindow", "m/s"))
        self.current_cnst_radioButton.setText(_translate("MainWindow", "Constant:"))
        self.current_dir_label.setText(_translate("MainWindow", "Dir.:"))
        self.current_dir_lnEdt.setToolTip(_translate("MainWindow", "0 ⩽ d° < 360"))
        self.current_dirUnit_label.setText(_translate("MainWindow", "North"))
        self.current_sal_label.setText(_translate("MainWindow", "Salinity:"))
        self.current_salUnit_label.setText(_translate("MainWindow", "PSU"))
        self.current_temp_label.setText(_translate("MainWindow", "Temp.:"))
        self.current_tempUnit_label.setText(_translate("MainWindow", "°C"))
        self.currentFrame_label.setText(_translate("MainWindow", "Current"))
        self.releaseFrame_label.setText(_translate("MainWindow", "Release"))
        self.release_output_lnEdt.setToolTip(_translate("MainWindow", "Directory to save the output files"))
        self.release_output_Btn.setText(_translate("MainWindow", "..."))
        self.release_endDate_label.setText(_translate("MainWindow", "Release End Date:"))
        self.release_pollutant_label.setText(_translate("MainWindow", "Pollutant:"))
        self.release_pollutant_file_label.setText(_translate("MainWindow", "Input File:"))
        self.release_pollutant_lnEdt.setToolTip(_translate("MainWindow", "Path to the AERCOARE input CSV file"))
        self.release_pollutant_file_Btn.setText(_translate("MainWindow", "..."))      
        self.release_longitude_label.setText(_translate("MainWindow", "Longitude:"))
        self.release_longitude_lnEdt.setToolTip(_translate("MainWindow", "-180 < d° ⩽ 180"))
        self.release_strtDate_label.setText(_translate("MainWindow", "Release Start Date:"))
        self.release_latDir_label.setText(_translate("MainWindow", "North"))
        self.release_lonDir_label.setText(_translate("MainWindow", "East"))
        self.release_amount_label.setText(_translate("MainWindow", "Amount Released:"))
        self.release_latitude_label.setText(_translate("MainWindow", "Latitude:"))
        self.release_latitude_lnEdt.setToolTip(_translate("MainWindow", "-90 ⩽ d° ⩽ 90"))
        self.releaseOutput_label.setText(_translate("MainWindow", "Output Directory:"))
        self.release_depth_label.setText(_translate("MainWindow", "Depth:"))
        self.release_depthUnit_label.setText(_translate("MainWindow", "Meters"))
        self.close_button.setText(_translate("MainWindow", "Close"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.menu_Menu.setTitle(_translate("MainWindow", "Menu", None))
        self.menu_Menu.menuAction().setStatusTip(_translate("MainWindow", "Click for more options", None))
        self.action_new.setText(_translate("MainWindow", "New", None))
        self.action_new.setStatusTip(_translate("MainWindow", "Resets fields and initiate a new job", None))
        self.action_about.setText(_translate("MainWindow", "About", None))
        self.action_about.setStatusTip(_translate("MainWindow", "Shows more info about this software suite", None))